Fullfill the page security.md
okp4/docs pull request #168
Opened 2022-12-18 00:05 UTC by StakeandRelax-Validator

Hello,
we try to add our contribution to setup with a bit of information the page security.md.
The informations are taken from evmos/cro/juno documentation with the adeguate corrections in name of binary and chain-id.
It could be improved further, but we think that the source documentations are well done, so it's a good point to start.
Hope you'll apreciate it
Wookie

2022-12-18 15:16 UTC, StakeandRelax-Validator commented
Added commit lint

2022-12-18 15:44 UTC, StakeandRelax-Validator commented
corrected all markdown errors

2022-12-19 09:16 UTC, ad2ien requested changes
🤩 thanks a lot!
Just some remarks regarding the rendering so that your work looks nice as it should 😉

2022-12-19 09:16 UTC, ad2ien commented on docs/nodes/kms.md
> +Set up a Key Management System for okp4 {synopsis}
Do you mean something like this?
```suggestion
## Synopsis
Set up a Key Management System for okp4
```

2022-12-19 09:16 UTC, ad2ien commented on docs/nodes/security.md
> +::: tip
```suggestion
:::tip
```

2022-12-19 09:16 UTC, ad2ien commented on docs/nodes/kms_ledger.md
> +- [Ledger device](https://shop.ledger.com/) {prereq}
Should `{prereq}` be interpreted in some way?
```suggestion
- [Ledger device](https://shop.ledger.com/)
```

2022-12-19 10:06 UTC, ad2ien approved these changes
🚀

2022-12-19 10:24 UTC, StakeandRelax-Validator commented
had to fix a bit of old commits subjects but now should be all correct. There is still commit c9ab9ba without lint, should I fix it also?

2022-12-28 15:47 UTC, ccamel commented
@StakeandRelax-Validator Thank you very much for your input, we really appreciate it.

From what I see, the git commits history is not clean, but what I can suggest, if you agree, is that I squash & merge in one commit your work on main. This will solve the history problem as well as potentially the commit messages.

2022-12-28 15:49 UTC, ccamel commented
@amimart need your approval.

2023-01-12 10:55 UTC, amimart approved these changes
That's a really great work, interesting and relevant, thank you so much for that! 🙏

2023-01-12 10:57 UTC, ccamel approved these changes
That's a really great piece of work. Thanks so much for your submission @StakeandRelax-Validator :sunglasses:

2023-01-12 11:03 UTC, merged