fix: center and resize illustrations
okp4/docs pull request #200
Opened 2023-02-22 14:38 UTC by YoanOKP4

I have center and resize the new illustrations on the whitepaper

2023-02-22 15:30 UTC, MdechampG approved these changes

2023-02-22 16:29 UTC, ccamel requested changes
Thanks for this improvement. I have some general remakrs on how to declare centered images in Docusaurus. These should be taken into consideration. Don't hesitate if you need help.

- use relative source URLs.
- use the alt attributes to specify the alternative text.
- don't forget to close the <img /> block.
- use the Infima dedicated class to center images.

(see one of the suggestion I made for better understanding).

2023-02-22 16:29 UTC, ccamel commented on docs/whitepaper/roles.md
> +</p>
Here's an improved version:

```suggestion
<div className="text--center">
  <img src="/img/content/whitepaper/Blockchain_Participant.webp" alt="Blockchain Participants" width="50%" />
</div>
```

2023-03-06 09:57 UTC, YoanOKP4 commented on docs/whitepaper/roles.md
> +</p>
@ccamel I update following your recommendations

2023-03-06 13:09 UTC, MdechampG approved these changes

2023-03-06 13:20 UTC, ManonPoint26 approved these changes

2023-03-08 13:03 UTC, ccamel commented
The CI fails but a fix is in progress with https://github.com/okp4/contracts/pull/133.

2023-03-10 10:45 UTC, amimart approved these changes

2023-03-10 10:52 UTC, fredericvilcot commented on docs/whitepaper/roles.md
> +</div>
Why all images get an arbitrary 50% `width`?

2023-03-10 13:41 UTC, fredericvilcot commented on docs/whitepaper/roles.md
> +</div>
@YoanOKP4 @ManonPoint26 
I think we should be sure of this point before merging, what do you think?

2023-03-10 13:44 UTC, YoanOKP4 commented on docs/whitepaper/roles.md
> +</div>
I resize all the illustration with a width of 50% because they are too big. I try in local with "Inspect Element" and the rendering is fine.

2023-03-10 14:05 UTC, fredericvilcot commented on docs/whitepaper/roles.md
> +</div>
ok if all images are too big and can't fit to small screens, that's fine 👌

2023-03-10 14:05 UTC, fredericvilcot approved these changes

2023-03-10 14:08 UTC, ccamel approved these changes
Great! Thanks :+1:

2023-03-10 14:10 UTC, merged