Make link orange
okp4/docs pull request #221
Opened 2023-05-04 14:46 UTC by Joce31

in progress :)

2023-05-09 09:32 UTC, MdechampG requested changes
Thanks @Joce31 !

Please could you make the following modifications : 
- Use the font in the mock up for the lateral bar 
- Reduce the thickness of the orange bar of the selected sub-section (lateral bar)
- Remove bold for selected section (header)

As discussed we don't need the language selector. You can remove it in another PR or in this one, as you prefer.

2023-05-12 11:12 UTC, Joce31 commented
remove the translator.
Reduce the thickness of the orange bar of the selected sub-section 
header : Remove bold for selected section.
change color sidebar (dark and white)

2023-05-12 11:44 UTC, MdechampG requested changes
Thank you @Joce31 ! 
Only thing to change : put the font Barlow 
And put bold on the selected sub-section (lateral bar)

2023-05-15 12:53 UTC, Joce31 commented
I've finish my tasks:
Put the font Barlow and put bold on the selected sub-section on lateral bar.

2023-05-15 14:38 UTC, fredericvilcot requested changes

2023-05-15 14:38 UTC, fredericvilcot commented on src/scss/main.scss
> +  .collapseSidebarButton_node_modules-\@docusaurus-theme-classic-lib-theme-DocSidebar-Desktop-CollapseButton-styles-module {
Where this `className` is coming from? 🧐

2023-05-15 14:38 UTC, fredericvilcot commented on docusaurus.config.js
You seem to have some format issues, please remove all unnecessary empty lines and commas 🙏

2023-05-15 14:38 UTC, fredericvilcot commented on sidebars.js
Same here, format issues

2023-05-15 14:38 UTC, fredericvilcot commented on src/scss/custom.scss
>    src: url("/static/fonts/Barlow/Barlow-Regular.ttf");
IMHO, this is not correct as your `bold` font-family still refers to `"/static/fonts/Barlow/Barlow-Regular.ttf"` source

2023-05-15 14:45 UTC, Joce31 commented on src/scss/main.scss
> +  .collapseSidebarButton_node_modules-\@docusaurus-theme-classic-lib-theme-DocSidebar-Desktop-CollapseButton-styles-module {
I'm sorry I couldn't find the classname so I had to check with christophe to force it :(

2023-05-15 14:51 UTC, Joce31 commented on docusaurus.config.js
i used this command:
"yarn stylelint '**/*.scss" and it's ok ! 
i'm review that

2023-05-16 14:52 UTC, Joce31 commented
remove the underline of homepage and add hover orange on title.
remove bold on paragraph and change the font-size of sidebar.

2023-05-17 05:54 UTC, MdechampG approved these changes
Thank you @Joce31 !
It looks good to me :)

2023-05-17 07:44 UTC, fredericvilcot commented on src/scss/custom.scss
> +  font-family: "Barlow regular Bold";
```suggestion
  font-family: "Barlow Bold";
```

2023-05-17 07:44 UTC, fredericvilcot commented on docusaurus.config.js
> +
To be removed

2023-05-17 07:45 UTC, fredericvilcot commented on docusaurus.config.js
> +          },
```suggestion
          }
```

2023-05-17 07:45 UTC, fredericvilcot commented on docusaurus.config.js
> +
To be removed

2023-05-17 07:45 UTC, fredericvilcot commented on docusaurus.config.js
> +        darkTheme: darkCodeTheme,
```suggestion
        darkTheme: darkCodeTheme
```

2023-05-17 07:45 UTC, fredericvilcot commented on docusaurus.config.js
> +        defaultMode: 'dark',
```suggestion
        defaultMode: 'dark'
```

2023-05-17 07:45 UTC, fredericvilcot commented on sidebars.js
> +  }],
```suggestion
  }]
```

2023-05-17 09:50 UTC, Joce31 commented on src/scss/custom.scss
> +  font-family: "Barlow regular Bold";
it's ok normally

2023-05-17 09:52 UTC, Joce31 commented on docusaurus.config.js
> +
it's ok!

2023-05-17 11:18 UTC, Joce31 commented on docusaurus.config.js
> +
it's ok.

2023-05-17 11:21 UTC, Joce31 commented on docusaurus.config.js
> +        darkTheme: darkCodeTheme,
remove the extra commas from the document.

2023-05-17 11:22 UTC, Joce31 commented on docusaurus.config.js
> +        defaultMode: 'dark',
it's ok

2023-05-17 11:22 UTC, Joce31 commented on sidebars.js
> +  }],
it's ok.

2023-05-17 11:26 UTC, Joce31 commented
After review of Fred i remove the extra spaces and extra comas.

2023-05-17 11:48 UTC, fredericvilcot commented
Thanks for the changes @Joce31 😎
Could you please sign your commit with a GPG key?

2023-05-22 09:22 UTC, fredericvilcot requested changes

2023-05-22 09:22 UTC, fredericvilcot commented on src/scss/custom.scss
> +  --ifm-heading-font-family: "Barlow regular", sans-serif;
Should be `Barlow bold` instead no?

2023-05-22 09:22 UTC, fredericvilcot commented on src/scss/custom.scss
> +  font-family: "Barlow Bold";
```suggestion
  font-family: "Barlow bold";
```

2023-05-22 09:22 UTC, fredericvilcot commented on src/scss/custom.scss
>    --ifm-font-family-base: "Barlow regular", sans-serif;
You have deleted the `font-face` `Barlow regular`, so IMHO, this won't work anymore..

2023-05-22 11:33 UTC, Joce31 commented on src/scss/custom.scss
> +  --ifm-heading-font-family: "Barlow regular", sans-serif;
sorry i corrected.

2023-05-22 11:34 UTC, Joce31 commented on src/scss/custom.scss
> +  font-family: "Barlow Bold";
i corrected.

2023-05-22 11:43 UTC, Joce31 commented on src/scss/custom.scss
>    --ifm-font-family-base: "Barlow regular", sans-serif;
sorry . i don't understand . if i change this color-primary, the colour "orange"  will not work on the light . can i have more explanation please.

2023-05-22 13:06 UTC, fredericvilcot commented on src/scss/custom.scss
>    --ifm-font-family-base: "Barlow regular", sans-serif;
I was saying that you use `"Barlow regular"` font for the `--ifm-font-family-base` variable, but, if I see the change in line 7, you have changed this font-face with a bold one.
So, the `Barlow regular` does not work anymore because it's declared nowhere.

2023-05-22 13:36 UTC, Joce31 commented on src/scss/custom.scss
>    --ifm-font-family-base: "Barlow regular", sans-serif;
Thank you, I hadn't thought about it.  but if I understand correctly I have to delete this line.

2023-05-22 13:41 UTC, fredericvilcot commented on src/scss/custom.scss
>    --ifm-font-family-base: "Barlow regular", sans-serif;
If this variable is used (and I think this is the case), I'll suggest to not remove it but to add a new font-face that will declare the `Barlow regular` font :)

2023-05-22 13:51 UTC, Joce31 commented on src/scss/custom.scss
>    --ifm-font-family-base: "Barlow regular", sans-serif;
Ok ! thanks .

2023-05-23 08:19 UTC, Joce31 commented
i've finished my tasks of review from Fred.
i've incresead the font-size of navbar as requested by Marine.
i've deleted the font of the meteorit in the "custom.css".

2023-05-23 08:58 UTC, MdechampG approved these changes
LGTM thank you :)

2023-05-30 07:49 UTC, merged