First tutorial: governance with Prolog
okp4/docs pull request #230
Opened 2023-06-12 11:57 UTC by antho31

* Overview with link to Prolog tutorial 
* Complete first tutorial, Prolog & `okp4d` commands
* `.markdownlint.yaml` updated to enable ordered lists with code blocks

2023-06-12 12:57 UTC, ccamel requested changes
Excellent tutorial ! I have a few minor comments that you can consider at your convenience.

2023-06-12 15:20 UTC, bdeneux requested changes
Wonderful tutorial ! 👏 Nice ! I just notice one mistake :D

2023-06-12 15:20 UTC, bdeneux commented on docs/tutorials/prolog-1.mdx
> +You can replace `—no admin` with `—admin YOUR_OKP4_ADDR` if you want to be able to “break” (to remove the stored program).
```suggestion
You can replace `—no-admin` with `—admin YOUR_OKP4_ADDR` if you want to be able to “break” (to remove the stored program).
```

2023-06-12 15:32 UTC, antho31 commented on docs/tutorials/prolog-1.mdx
> +You can replace `—no admin` with `—admin YOUR_OKP4_ADDR` if you want to be able to “break” (to remove the stored program).
Thanks for your feedback, and wow good point :) !

2023-06-12 16:28 UTC, amimart requested changes
That's really great! 💪

2023-06-12 16:28 UTC, amimart commented on docs/tutorials/prolog-1.mdx
> +You can replace `—no-admin` with `—admin YOUR_OKP4_ADDR` if you want to be able to “break” (to remove the stored program).
```suggestion
Replace the `--from` value by your wallet name. You can also change the `--label` name as you want but note it should be unique.
You can replace `--no-admin` with `--admin YOUR_OKP4_ADDR` if you want to be able to “break” (to remove the stored program).
```

2023-06-12 20:58 UTC, bdeneux approved these changes

2023-06-14 06:33 UTC, MdechampG approved these changes

2023-06-14 06:36 UTC, merged