New whitepaper - introduction
okp4/docs pull request #231
Opened 2023-06-13 08:39 UTC by tpelliet

- New intro added
- New whitepaper architecture added
- Old whitepaper removed

- Missing: Introduction images

2023-06-13 11:05 UTC, MdechampG commented on docs/whitepaper/introduction.md
> +This is where the decentralized web steps in, capable of reshuffling the cards in terms of knowledge creation and dissemination. The decentralized web holds the key for a fair and trusted infrastruct
```suggestion
This is where the decentralized web steps in, capable of reshuffling the cards in terms of knowledge creation and dissemination. The decentralized web holds the key for a fair and trusted infrastructure to share any existing datasets and algorithms, while tokens give innovating tools to incentivize collaboration. Within this context, OKP4 sets out to capitalize on the virtues of both Web 2.0 and Web 3.0 with the goal of propelling the knowledge economy to the next level.
```

2023-06-13 11:19 UTC, MdechampG commented on docs/whitepaper/introduction.md
> +Given the sensitivity of the data and knowledge sector, it's crucial that the infrastructure is as resilient and neutral as possible. Moreover, due to the intricacy of this field, there's a specific
```suggestion
Given the sensitivity of the data and knowledge sector, the infrastructure must be as resilient and neutral as possible. Moreover, due to the intricacy of this field, there's a specific design requirement that fosters sharing while managing these complexities efficiently.
```

2023-06-13 11:21 UTC, MdechampG commented on docs/whitepaper/introduction.md
> +- Other notable initiatives to valorize data include for exemple [Ocean Protocol](https://oceanprotocol.com/) specializing in data markets, [DIMO](https://dimo.zone/) incentivizing vehicule data shar
```suggestion
- Other notable initiatives to valorize data include for exemple [Ocean Protocol](https://oceanprotocol.com/) specializing in data markets, [DIMO](https://dimo.zone/) incentivizing vehicule data sharing or [Hivemapper] incentivizing mapping data collection.
```

2023-06-13 11:25 UTC, MdechampG commented on docs/whitepaper/introduction.md
> +From a technical standpoint, OKP4 offers a unique solution, deftly combining the virtues of openness and decentralization with the adaptive potential of interoperability and modularity.
```suggestion
From a technical standpoint, OKP4 offers a unique solution, deftly combining the virtues of **openness** and **decentralization** with the adaptive potential of **interoperability** and **modularity**.
```

2023-06-14 07:18 UTC, ccamel approved these changes

2023-06-14 07:22 UTC, amimart requested changes

2023-06-14 07:22 UTC, amimart commented on docs/whitepaper/introduction.md
> +This is where the decentralized web steps in, capable of reshuffling the cards in terms of knowledge creation and dissemination. The decentralized web holds the key for a fair and trusted infrastruct
```suggestion
This is where the decentralized web steps in, capable of reshuffling the cards in terms of knowledge creation and dissemination. The decentralized web holds the key for a fair and trusted infrastructure to share any existing dataset and algorithms, while tokens give innovating tools to incentivize collaboration. Within this context, OKP4 sets out to capitalize on the virtues of both Web 2 and Web 3 with the goal of propelling the knowledge economy to the next level.
```

I think Web3 and Web3.0 have different meanings

2023-06-14 07:25 UTC, MathieuConte approved these changes

2023-06-14 07:55 UTC, MdechampG approved these changes

2023-06-14 09:54 UTC, merged