Add architecture part in the Whitepaper
okp4/docs pull request #237
Opened 2023-06-16 14:51 UTC by antho31

Here's the first version of the "Architecture" section of the whitepaper.  
* Overall architecture (updated schema since our meeting on June 14)
* Mermaid sequence diagram from the end-to-end example 

Note that texts and schemas have not been fully validated. There are some fuzzy points. It may be worth publishing this to help developers for the Builders Program... 

What are your points?

2023-06-17 14:20 UTC, ccamel requested changes
Great job. I left some comments. There are indeed some inaccuracies and uncertainties in some paragraphs that need to be addressed. We can have a meeting to discuss them together, with @amimart.

2023-06-17 14:20 UTC, ccamel commented on docs/whitepaper/architecture.mdx
> +`zone-hub` also handles state reportings from orchestration executions. It redirects messages to `pactum` instances.
Nope. See previous comment. It stores this to the `cognitarium` (after validating the data provided).

2023-06-17 14:20 UTC, ccamel commented on docs/whitepaper/architecture.mdx
> +1. Each on their own, Corp A and Corp B indicate through an administration portal the underlying technology of their respective database. They store access tokens with a Secret Management Service, wi
This is not clear to me. As I understand it, service C accesses the authentication key to gain authorization for data consumption. However, for both protocol mediation and security mediation purposes, access to this key should only be possible by the Orchestration service's identity alone within the context of a properly registered execution order within the protocol.

2023-06-18 12:58 UTC, antho31 commented on docs/whitepaper/architecture.mdx
> +1. Each on their own, Corp A and Corp B indicate through an administration portal the underlying technology of their respective database. They store access tokens with a Secret Management Service, wi
I initially differentiated the service/algo provided by C from the orchestration service as two different "actors". Then I realized, especially with the sequence diagram, that it was overloading the whole. 

What would you suggest: make a clear difference between these two services, or explain with a phrase that we combine to simplify, to make it more readable?

2023-06-19 09:31 UTC, antho31 commented on docs/whitepaper/architecture.mdx
> +Prolog code defines governance rules, the “law”. These pieces of logic programming (usually from `.pl` files) are stored in raw with an `objectarium` smart contract, which acts as a file system.
Updated: 

### Objectarium: unstructured data storage

The main goal of `objectarium` is to provide the protocol with a versatile mechanism for storing unstructured data, ensuring that the stored data remains immutable.

Any user or smart contract can ”pin” a stored object. Object deletion is impossible as long as it contains at least one “pin”. The user (or smart contract) should use the “unpin” function from `objectarium` to remove a pin.

A specific use case is the storing governance rules as a Prolog program. Prolog code defines governance rules, the “law”. These pieces of logic programming (usually from `.pl` files) are stored in raw with an `objectarium` smart contract.

2023-06-19 09:33 UTC, antho31 commented on docs/whitepaper/architecture.mdx
> +Prolog code defines governance rules, the “law”. These pieces of logic programming (usually from `.pl` files) are stored in raw with an `objectarium` smart contract, which acts as a file system.
I agree. We should check (in code comments, ...) to remove any "file system" reference for consistency.

2023-06-19 09:35 UTC, antho31 commented on docs/whitepaper/architecture.mdx
> +* Ontology: the knowledge graph modelling all the different resources (e. g. datasets, computation services, infrastructure, orchestration engines, …), their descriptive properties and relations betw
✔️

2023-06-19 09:41 UTC, antho31 commented on docs/whitepaper/architecture.mdx
> +* Orchestration: the processes that check the access conditions compliance defined by entities. Orchestration relates to resource authorisation controls and revenue-sharing distribution.
Updated: 

### Smart contract overview

Smart contracts handle all interactions with external parties, whether to provide a digital resource with condition rules to use it, to consume this resource, or to send payments. These decentralized programs are centered around three fundamental pillars:

* **Ontology**: models all the different resources (e. g. datasets, computation services, infrastructure, orchestration engines, …), their descriptive properties and relations between each other.  
It also includes access rules and execution instructions linked to resources. The ontology is a whole of objects, a way to store a semantic representation of the Dataverse.
* **Governance**: statutes the definition and the validation of resource permissions.  
Rules (i.e. the conditions to give access to resources) can be applied at one among multiple levels: for everyone, for a set of resources, for a specific resource or between selected parties only.
* **Orchestration**: ensures the smooth coordination and execution of services.  
It enforces the rules and policies that govern resource (datasets and services) authorization.

2023-06-19 09:46 UTC, antho31 commented on docs/whitepaper/architecture.mdx
> +The logic module has a virtual file system built in. Users can store Prolog programs and add a reference to another Prolog program. It enhances reusability and composability.
OK I deleted these two sentences

2023-06-19 09:49 UTC, antho31 commented on docs/whitepaper/architecture.mdx
> +Any smart contract deployed on the OKP4 blockchain uses the logic module to evaluate sharing conditions definitions and user access queries written in Prolog. Prolog is a powerful declarative program
I forgot "can". 
Updated: 
"Thus, any smart contract deployed on the OKP4 blockchain can use the logic module to evaluate queries written in Prolog."

2023-06-19 09:51 UTC, antho31 commented on docs/whitepaper/architecture.mdx
> +There is no restriction on the structure to allow ample expressiveness. But the OKP4 “core”, the minimal ontology scheme, requires the specification of an explicit relationship between an external re
Thanks, I didn't succeed in putting words on it.

2023-06-19 09:58 UTC, antho31 commented on docs/whitepaper/architecture.mdx
> +A `pactum` instance records service execution states and applies token revenue-sharing distribution if conditions are met. It can also flag invalid service execution and block escrow in consequence.
Updated: not quite sure. Is it OK?

### Pactum: service agreement contract

This smart contract guarantees the orchestration, the respect of the law and the value allocations.

A `pactum` instantiation defines an agreement between at least two parties and details the prerequisites that fulfil its enforcement and the actions to proceed accordingly. These conditions to execute contractual obligations are materialized as a set of terms previously stored with the `law-stone` smart contract.  

Service execution states are recorded in the ontology, forming the knowledge graph in `cognitarium`. The evaluation of conditions that must be met within the agreement changes over time based on the "facts" are also recorded in the ontology. Thus, a `pactum` instance applies token revenue-sharing distribution if conditions are met. It can also flag invalid service execution and block escrow in consequence.

2023-06-19 10:02 UTC, antho31 commented on docs/whitepaper/architecture.mdx
> +This smart contract guarantees the orchestration, the respect of the law and the value allocations.
✔️

2023-06-19 10:04 UTC, antho31 commented on docs/whitepaper/architecture.mdx
> +`zone-hub` also handles state reportings from orchestration executions. It redirects messages to `pactum` instances.
Updated:

`zone-hub` also handles state reportings from orchestration executions. It stores messages in a `cognitarium` instances, before an evaluation by a `pactum` instance.

2023-06-19 14:00 UTC, amimart requested changes
Thanks !

Here's a first review, I didn't check everything in details though :)

2023-06-19 14:00 UTC, amimart commented on docs/whitepaper/architecture.mdx
> +A consumer asks the blockchain through an app to compute a query using multiple resources. If the rules set by the providers are met, the protocol emits an event to validate the query.
The term `query` isn't exact as it refers usually to read operations, the intent here is more an `execution request`. The diagram above contains references to this term also.

2023-06-19 14:00 UTC, amimart commented on docs/whitepaper/architecture.mdx
> +![OKP4 Basic Architecture Overview](/img/content/whitepaper/arch-basic.webp)
I'm not sure about the 4th step definition in the diagram: `report usage`.

It is more than a usage, it's a status. It shall contains any relevant information regarding execution, not only usage.

2023-06-19 14:00 UTC, amimart commented on docs/whitepaper/architecture.mdx
> +![OKP4 Architecture Schema](/img/content/whitepaper/arch-overview.webp)
The docker icon on the workflow engine bothers me, it's incompatible with the _"Anything as a Service"_ approach.

The arrows coming out of the blockchain are problematic for me as it suggests an action from the blockchain onto the external world. I understand this diagram is an overview and not precise, but this is false.

2023-06-19 14:00 UTC, amimart commented on docs/whitepaper/architecture.mdx
> +`zone-hub` is the unique interface with the off-chain interfaces for any blockchain interaction. This smart contract operates external requests and calls the other smart contracts methods. It checks
I would say that it's the single entrypoint to any mutations in the protocol, for example nothing prevents to query the `cognitarium` or a `law-stone` directly.

Regarding the term `authentication`, I think a proper word would be `authorization`.

2023-06-19 14:00 UTC, amimart commented on docs/whitepaper/architecture.mdx
> +When a consumer submits a query, the `zone-hub` instance evaluates the required resources with a request to `cognitarium`. It extracts the governance rules, and, to evaluate resource access, it asks
Same as above regarding the `query` term :)

2023-06-19 14:00 UTC, amimart commented on docs/whitepaper/architecture.mdx
> +Initially, there will be a unique orchestration service, a central “workflow engine”.
Yes, an orchestration service should be able to access other off-chain resources in order to fulfill its task, executing a workflow. But the OKP4 blockchain doesn't execute jobs, and initially, who says there will be a unique orchestration service? 👀

2023-06-19 14:00 UTC, amimart commented on docs/whitepaper/architecture.mdx
> +The final result of the execution is returned to the user’s endpoint, which can visualize the new knowledge through BI components, for example.
I think the execution result is defined in the workflow, it may be integrated as a new dataset in the protocol or sent elsewhere outside the control of the protocol if the rules allows it.

2023-06-20 07:36 UTC, MdechampG requested changes
Thank you @antho31 ! Here are few typos.

2023-06-20 07:36 UTC, MdechampG commented on docs/whitepaper/architecture.mdx
> +Once inserted via the `cognitarium` smart contract, one can fetch the data from a “select” or a “describe” query. In the first case, it returns resources matching the criterias defined by the provide
```suggestion
Once inserted via the `cognitarium` smart contract, one can fetch the data from a “select” or a “describe” query. In the first case, it returns resources matching the criteria defined by the provided query. The second case returns the raw part of the ontology, the resource description identified by an Internationalized Resource Identifier (IRI).
```

2023-06-20 07:36 UTC, MdechampG commented on docs/whitepaper/architecture.mdx
> +* **Ontology**: models all the different resources (e. g. datasets, computation services, infrastructure, orchestration engines, …), their descriptive properties and relations between each other.
```suggestion
* **Ontology**: models all the different resources (e. g. datasets, computation services, infrastructure, orchestration engines, …), their descriptive properties and relations with each other.  
```

2023-06-20 07:36 UTC, MdechampG commented on docs/whitepaper/architecture.mdx
> +6. The orchestration service listens the event from the blockchain. It recovers access keys, and then executes the workflow training algorithm from Corp C, using Corp A & Corp B data it fetches.
```suggestion
6. The orchestration service listens to the event from the blockchain. It recovers access keys, and then executes the workflow training algorithm from Corp C, using Corp A & Corp B data it fetches.
```

2023-06-20 10:23 UTC, antho31 commented
Thanks, @amimart & @MdechampG, for your complete and relevant feedback! The last commit integrates all the suggested changes, it includes updated schemas too.

2023-06-21 09:59 UTC, tpelliet commented on docs/whitepaper/architecture.mdx
> +A consumer asks the blockchain through an app to execute a request using multiple resources. If the rules set by the providers are met, the protocol emits an event to validate the request.
and the zone?

2023-06-22 13:57 UTC, antho31 commented
Updated with schemas from Lisa. 
Can you publish this new part of the WP?

2023-06-23 09:28 UTC, ccamel commented on docs/whitepaper/architecture.mdx
> +7. The orchestration service reports the job state changes. If all works well, service agreement rules are applied, $KNOW tokens from Individual D are unlocked to Corp A, Corp B et Corp C.
```suggestion
7. The orchestration service tracks the progress and state changes of all jobs within the workflow and reports this information to the blockchain. If all works well, service agreement rules are applied, $KNOW tokens from Individual D are unlocked to Corp A, Corp B et Corp C.
```

2023-06-23 09:49 UTC, ccamel approved these changes

2023-06-23 11:20 UTC, amimart approved these changes

2023-06-23 11:50 UTC, MdechampG approved these changes

2023-06-23 11:53 UTC, merged