Feat/wp roles
okp4/docs pull request #250
Opened 2023-06-28 13:26 UTC by MathieuConte

Here, the version of the `Roles` part of the Whitepaper.

<img width="1302" alt="image" src="https://github.com/okp4/docs/assets/9574336/77344055-818a-4a55-a3a8-85df553eaa8b">

2023-06-28 16:11 UTC, MdechampG requested changes
Thank you @MathieuConte !
Few typos but almost good 💪🏻

2023-06-28 16:11 UTC, MdechampG commented on docs/whitepaper/roles.md
> +Delegators engage with the protocol by delegating their tokens to Validators. However, they can manually “retrieve” their voting rights and directly participate in governance through specific transac
```suggestion
Delegators engage with the protocol by delegating their tokens to Validators. However, they can manually “retrieve” their voting rights and directly participate in governance through specific transaction.
```

2023-06-28 16:11 UTC, MdechampG commented on docs/whitepaper/roles.md
> +They are responsible  describing dataset characteristics (metadata) and for establishing consent rules for the use of this resource . They are solely authorized to modify these rules unless they deci
```suggestion
They are responsible  describing dataset characteristics (metadata) and for establishing consent rules for the use of this resource . They are the only ones authorized to modify these rules unless they decide otherwise through these rules of consent. They may also receive compensation from Consumers each time their data is used or purchased, according to the associated governance rules.
```

2023-06-28 16:11 UTC, MdechampG commented on docs/whitepaper/roles.md
> +Service Providers are responsible for providing services, defining consent rules, describing services, and setting up remuneration models based on the nature and usage of their resources. depending o
```suggestion
Service Providers are responsible for providing services, defining consent rules, describing services, and setting up remuneration models based on the nature and usage of their resources. Depending on consent rules and Zone rules, service providers may be required to stake tokens to ensure service availability and integrity.
```

2023-06-28 16:11 UTC, MdechampG commented on docs/whitepaper/roles.md
> +Service Providers interact with the protocol by referencing their services and consent rules via smart contracts, ensuring the availability and functioning of their service in accordance with on-chai
```suggestion
Service Providers interact with the protocol by referencing their services and consent rules via smart contracts, ensuring the availability and functioning of their service in accordance with on-chain registered specifications. Furthermore, retribution fees may be distributed to service providers, according with established consent rules and zone rules.
```

2023-06-28 16:11 UTC, MdechampG commented on docs/whitepaper/roles.md
> +They interact with the protocol via dedicated smart contracts to register datasets, establish their consent rules and characteristics, and make the dataset available and accessible. In addition, retr
```suggestion
They interact with the protocol via dedicated smart contracts to register datasets, establish their consent rules and characteristics, and make the dataset available and accessible. In addition, retribution fees may be distributed to data providers, in accordance with established consent rules and zone rules.
```

2023-06-28 18:47 UTC, ccamel approved these changes
Great! Tested locally, and the rendering LGTM. :+1:

2023-06-28 19:41 UTC, antho31 approved these changes

2023-06-29 06:16 UTC, amimart approved these changes
💪

2023-06-29 08:32 UTC, MdechampG approved these changes

2023-06-29 08:48 UTC, merged