feat: docs use cases
okp4/docs pull request #257
Opened 2023-07-05 15:44 UTC by jeremylgn

Self explanatory.

2023-07-05 17:56 UTC, ccamel requested changes
A few comments and suggestions ready to be incorporated. If it's okay for you, you add the "Suggested changes" in a batch and commit it.

2023-07-05 17:56 UTC, ccamel commented on docs/whitepaper/use cases.md
> +The global Carbon Credit Market is projected to grow remarkably, from USD **414.8 billion in 2023 to USD 1,602.7 billion by 2028, with a staggering CAGR of 31.0%.** This exponential growth reflects t
IMHO, placing a link directly within a title is uncommon and, I guess, not considered a good practice in Markdown. I would position the title in the paragraph directly.

```suggestion
### Market

The global [Carbon Credit Market](https://www.globenewswire.com/en/news-release/2023/04/18/2648655/0/en/Carbon-Offset-Carbon-Credit-Market-Size-Projected-to-Reach-1-602-7-Billion-by-2028-MarketsandMarkets.html) is projected to grow remarkably, from USD **414.8 billion in 2023 to USD 1,602.7 billion by 2028, with a staggering CAGR of 31.0%.** This exponential growth reflects the growing recognition of the importance of carbon offsetting in combating climate change and achieving net-zero greenhouse gas emissions.
```

2023-07-05 17:56 UTC, ccamel commented on docs/whitepaper/use cases.md
> +3. **Processing and calculation** (GHG Protocol, VCS Protocol, Gold Standard, reference data, conversion factors) under different categories (scope 1: direct emissions, scope 2: energy-related indire
```suggestion
1. **Data Collection** from various sources (ERP, CSR, etc.), actors (suppliers, clients, etc.), and formats (IoT sensors, meters, energy management systems, etc.).
2. **Aggregation and normalization** conversion services, standardization, quality, joining services).
3. **Processing and calculation** (GHG Protocol, VCS Protocol, Gold Standard, reference data, conversion factors) under different categories (scope 1: direct emissions, scope 2: energy-related indirect emissions, scope 3: upstream and downstream indirect emissions).
```

2023-07-05 17:56 UTC, ccamel commented on docs/whitepaper/use cases.md
> +Transparency issues apply to the whole field of AI. According to [Next Move Strategy Consulting](https://www.nextmsc.com/), the artificial intelligence market is expected to grow strongly in the comi
Same here for the link in the title.

Suggestion:

```suggestion
### Market

Transparency issues apply to the whole field of AI. According to [Next Move Strategy Consulting](https://www.nextmsc.com/), the [artificial intelligence market](https://www.statista.com/statistics/1365145/artificial-intelligence-market-size/#:~:text=According%20to%20Next%20Move%20Strategy,a%20vast%20number%20of%20industries) is expected to grow strongly in the coming decade. Its nearly $100 Billion U.S. value is expected to grow twentyfold by 2030, up to almost two trillion U.S. dollars. The AI market covers a vast number of industries. Everything from supply chains, marketing, product making, research, analysis, and more are fields that will, in some aspect, adopt artificial intelligence within their business.
```

2023-07-05 17:56 UTC, ccamel commented on docs/whitepaper/use cases.md
> +Example :
```suggestion
*Example:*
```

2023-07-05 17:56 UTC, ccamel commented on docs/whitepaper/use cases.md
> + A Machine Learning company could use specifically some of these stream data to propose a new summary. Everyone could know from which publishers the summary is from. For each summary consumption, rev
```suggestion

A Machine Learning company could use specifically some of these stream data to propose a new summary. Everyone could know from which publishers the summary is from. For each summary consumption, revenue sharing is applied between every concerned publisher.
```

2023-07-05 17:56 UTC, ccamel commented on docs/whitepaper/use cases.md
> +Estimating the market size on a broad subject, such as organizations and communities, is difficult. Instead, let's deep dive into Decentralized Autonomous Organization (D.A.O.). As of January 2023, t
Same here for the link in the title.

Suggestion:

```suggestion
### Market

Estimating the market size on a broad subject, such as organizations and communities, is difficult. Instead, let's deep dive into Decentralized Autonomous Organization (D.A.O.). As of January 2023, the total market capitalization of the [D.A.O. market](https://daotimes.com/6-interesting-dao-insights-from-2022/) stood at $8.8 billion. The total number of decentralized organizations stood at an impressive 10,752, up from 4,830 organizations in three months.
```

2023-07-05 17:56 UTC, ccamel commented on docs/whitepaper/use cases.md
> +Thanks to the protocol, the group will formalize and build an initial workflow enabling a tool for analyzing and synthesizing discussions referenced in the Dataverse. The first stage of collecting di
```suggestion
Thanks to the protocol, the group will formalize and build an initial workflow enabling a tool for analyzing and synthesizing discussions referenced in the Dataverse. The first stage of collecting discussions is implemented. Then these are aggregated and processed using text analysis and natural language processing tools according to the needs of the working group. Then, based on this analysis, a summary is created to facilitate understanding of all this information and made accessible to all members.
```

2023-07-05 17:56 UTC, ccamel commented on docs/whitepaper/use cases.md
> +**IoT and PoPW network as a Service**
```suggestion
### IoT and PoPW network as a Service
```

2023-07-05 17:56 UTC, ccamel commented on docs/whitepaper/use cases.md
> +**Agriculture**
```suggestion
### Agriculture
```

2023-07-05 17:56 UTC, ccamel commented on docs/whitepaper/use cases.md
> +**Health**
```suggestion
### Health
```

2023-07-05 17:56 UTC, ccamel commented on docs/whitepaper/use cases.md
> +**Industry**
```suggestion
### Industry
```

2023-07-05 17:56 UTC, ccamel commented on docs/whitepaper/use cases.md
> +**AI**
```suggestion
### AI
```

2023-07-05 17:56 UTC, ccamel commented on docs/whitepaper/use cases.md
> +## 1. OKP4: Pioneering a sustainable revolution in Carbon Credit Management
In the rest of the whitepaper, the titles are not numbered. I therefore propose not to do so here, for consistency's sake.

```suggestion
## OKP4: Pioneering a sustainable revolution in Carbon Credit Management
```

2023-07-06 08:13 UTC, antho31 reviewed
Reference to the Architecture part suggestion

2023-07-06 08:13 UTC, antho31 commented on docs/whitepaper/use cases.md
> +8. The orchestration service stores the result in the provided Individual D's storage solution. Optionally, this new knowledge can also be referenced as a data source for other workflows. Individual
```suggestion
A complete description of end-to-end ML training with the OKP4 protocol is available in [the technical part of the whitepaper](https://docs.okp4.network/whitepaper/architecture#connectem-all). 
```

2023-07-06 08:23 UTC, JulienMassonnat commented on docs/whitepaper/use cases.md
> +Example :
Yes I think it's important that we explained the use case with an accurate workflow. It's not so technical, it's just not sexy (Corp A, Corp B, etc.).

2023-07-06 08:48 UTC, antho31 commented on docs/whitepaper/use cases.md
> +Example :
OK, so we have two distinct examples, one more "evasive" and another more detailed?

2023-07-06 09:39 UTC, jeremylgn commented on docs/whitepaper/use cases.md
> +## 1. OKP4: Pioneering a sustainable revolution in Carbon Credit Management
Done :heavy_check_mark:

2023-07-06 09:39 UTC, jeremylgn commented on docs/whitepaper/use cases.md
> +The global Carbon Credit Market is projected to grow remarkably, from USD **414.8 billion in 2023 to USD 1,602.7 billion by 2028, with a staggering CAGR of 31.0%.** This exponential growth reflects t
Done :heavy_check_mark:

2023-07-06 09:40 UTC, jeremylgn commented on docs/whitepaper/use cases.md
> +3. **Processing and calculation** (GHG Protocol, VCS Protocol, Gold Standard, reference data, conversion factors) under different categories (scope 1: direct emissions, scope 2: energy-related indire
Done :heavy_check_mark:

2023-07-06 09:40 UTC, jeremylgn commented on docs/whitepaper/use cases.md
> +## 2. Transparent & Fair Model Training (Ml & AI)
Done :heavy_check_mark:

2023-07-06 09:40 UTC, jeremylgn commented on docs/whitepaper/use cases.md
> +Transparency issues apply to the whole field of AI. According to [Next Move Strategy Consulting](https://www.nextmsc.com/), the artificial intelligence market is expected to grow strongly in the comi
Done :heavy_check_mark:

2023-07-06 11:30 UTC, ccamel approved these changes
LGTM! Thanks :+1:

2023-07-06 11:56 UTC, LucasPzn approved these changes
Looks good to me 👍

2023-07-06 12:02 UTC, ManonPoint26 approved these changes

2023-07-06 12:03 UTC, ManonPoint26 commented
Yes 👍

2023-07-06 12:25 UTC, antho31 approved these changes

2023-07-06 12:46 UTC, amimart approved these changes

2023-07-06 13:13 UTC, JulienMassonnat approved these changes

2023-07-06 14:21 UTC, merged