Docs: Replace broken, sprawling `jsonschema2md` output with 3 compact guides generated by Fadroma
okp4/docs pull request #276
Opened 2023-07-23 00:06 UTC by egasimus

I wrote a custom JSONSchema renderer over the last few days; it can be found [here](https://github.com/hackbg/fadroma/blob/feat/schema-tool/page/schema.mjs).

The script is native ES with zero dependencies, so it imposes no new limitations on the doc gen workflow. It can be copied it into the repo, or (once published), it can be consumed from a JS CDN on Node 18+.

The goal was to remove all things that are not relevant to practical usage of the contract API. For example:

<table>
<tr>
<td valign="top">

As an API consumer, I care about literally none of this JSONSchema metadata which is on every page of the current docs:

![Screenshot from 2023-07-23 02-16-14](https://github.com/okp4/docs/assets/1656054/cb961a8c-5fe7-47dd-8938-d2499734f590)

</td>
<td valign="top">

And why does each string constant/enum variant need its own page just to be mentioned in the corner at the end of it?

![Screenshot from 2023-07-23 02-16-34](https://github.com/okp4/docs/assets/1656054/36282f0a-3323-4477-afca-d0f8b85d88f5)

</td>
</tr>
</table>

Instead, let's keep the original JSON schemas available to anyone who has a preferred JSON Schema viewer, or wants to use the schemas for validation, etc.

But let's also generate a more concise Markdown overview of each contract and make *that* the API reference. Here's what those Markdowns look like, as of today.

* JSONSchema->MD by [Fadroma Schema Renderer](https://github.com/hackbg/fadroma/blob/feat/schema-tool/page/schema.mjs)
* MD->HTML by HedgeDoc (will try renering `okp4/docs` next):

<table>
<tr>
<td valign="top">

Invaluable benefit of throwing out the frameworks: once again, things start at the beginning.

![Screenshot from 2023-07-23 02-43-31](https://github.com/okp4/docs/assets/1656054/cc041940-610f-42da-a434-09f04d95733d)

</td>
<td valign="top">

Compact yet detailed descriptions, incl. enum definitions and cross-linking of non-primitive types:

![Screenshot from 2023-07-23 02-44-11](https://github.com/okp4/docs/assets/1656054/0fbad7c2-bf9f-48b6-b7d5-ee0db8de6c04)

</td>
</tr>

<tr>
<td valign="top">

All messages of a kind are in one place:

![Screenshot from 2023-07-23 02-33-51](https://github.com/okp4/docs/assets/1656054/df4bd193-e27b-4eda-8393-380d7f5a59fa)

</td>
<td valign="top">

More type definitions (previously affected by https://github.com/okp4/docs/issues/273) now render correctly - even the newlines in the tables.

![Screenshot from 2023-07-23 02-34-00](https://github.com/okp4/docs/assets/1656054/7001801b-8f49-4fed-98a6-14d7735ee1fb)

</td>
</tr>
<tr>
<td valign="top">

Same as above but some `Execute` messages:

![Screenshot from 2023-07-23 03-03-51](https://github.com/okp4/docs/assets/1656054/bd316bd8-f442-4647-9823-0b012cd52aeb)

</td>
<td valign="top">

As a finisher, here's how much code it takes (total, no dependencies other than Node):

![Screenshot from 2023-07-23 03-01-08](https://github.com/okp4/docs/assets/1656054/49619bdc-3e70-4634-8c7e-a5effeae67bf)

</td>
</tr>
</table>

Overall, I'm quite happy with how this doc rendering thingy is turning out. I believe this format of API docs makes it way easier to find info on how to interact with the contracts, and is much closer to what a newcomer would need to get started with the OKP4 platform.

Please review this PR and point out if something is missing, wrong, or needs to be clarified further.

P.S. Progress on the interactive schema-browser that I mentioned in #273 can be followed [here](https://github.com/hackbg/fadroma/pull/189#issuecomment-1646690774) - and it looks even better than the Hedgedoc screenshots ;-) Since its stack is slightly more complex, for now let's see how the Markdowns go though

2023-07-29 17:04 UTC, ccamel commented
@egasimus AFAIU, the job `report-new-dependencies` relies on organization secrets to be authorized for posting comments in the Pull Request regarding any potential changes made to the `package.json` file. Nevertheless, since your repository is a fork, GitHub does not transmit these secrets for security reasons, resulting in the failure of the job (with error: `Error: Parameter token or opts.auth is required`).

No worries. We can go through this error and still proceed with the merge.

2023-07-29 17:21 UTC, ccamel commented
@egasimus My feedback: The result is impressive, and I love the presentation of the documentation, which is not only readable but also highly useful and capable of enhancing the Developer Experience (DX)! :star_struck: 

After the initial review with @amimart, we identified the following areas for improvement:

- Some links are not functioning correctly. For instance, in the documentation of `cognitarium` (http://localhost:3000/contracts/okp4-cognitarium), the link to `StoreLimitsInput` (http://localhost:3000/contracts/okp4-cognitarium#StoreLimitsInput) is not working.
- I wonder if we can improve the code formatting. For example, the JSON code here: http://localhost:3000/contracts/okp4-cognitarium#executemsgdeletedata.
- Additionally, I believe there is room for improvement in the source code documentation, specifically in the smart contracts' code, to provide more detailed comments. But this is more on our side.

2023-08-11 13:05 UTC, bdeneux requested changes
Hey @egasimus ! Sorry for the delay ! That seems wonderful for the rendering 😍. 

On the other hand I prefer to remove all the rendering (`render.sh`) generation from this `docs` repository. I suggest you to remove it and let the new generated documentation like you have done. The generation should be done inside the `contracts` repository (in the [makefile](https://github.com/okp4/contracts/blob/main/Makefile.toml#L99-L133)), because it could be useful inside this repository to have a well formatted documentation (like is done today with `json2schema`). Then once the contracts is released, `docs` repository will fetch and updated the contracts documentation with the new generated ones. 

I can take care of the `contracts` parts if you want.

2023-09-07 13:28 UTC, antho31 commented
Let's keep as it is, with the footer :)

2023-09-07 13:28 UTC, antho31 approved these changes
Good job!

2023-09-07 13:33 UTC, amimart approved these changes
Awesome, thank you for bringing this, it has great value 🙏

2023-09-07 13:35 UTC, ccamel approved these changes
Great! Thanks so much :heart:

2023-09-07 13:37 UTC, bdeneux approved these changes
Thanks for this 🙏 ! Nice 👍

2023-09-07 13:41 UTC, merged