refactor(style): update header nav items hover color
okp4/docs pull request #284
Opened 2023-08-03 09:26 UTC by houssemmimoun27

This PR update the hover colour of the header nav items.

<details>

<summary> Screenshots </summary>

![Screenshot 2023-08-03 at 10 24 51](https://github.com/okp4/docs/assets/93918596/4e40fbe4-cf99-4184-8e48-b47d952e346f)

</details>

2023-08-03 11:35 UTC, MdechampG approved these changes
Looks good thank you !

2023-08-03 18:17 UTC, ccamel requested changes

2023-08-03 18:17 UTC, ccamel commented on src/scss/main.scss
> +    border-color: #00b6b7 transparent;
I don't quite see the point of this rule. If you could explain it.

2023-08-03 18:17 UTC, ccamel commented on src/scss/main.scss
> +  }
Since multiple selectors share the same style definitions, I think you can group them together to reduce repetition ([DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)), even more so when using [SCSS](https://sass-lang.com/).

2023-08-04 08:25 UTC, houssemmimoun27 commented on src/scss/main.scss
> +    border-color: #00b6b7 transparent;
This rule is for updating the hover color of the arrow icon.

![Screenshot 2023-08-04 at 09 29 05](https://github.com/okp4/docs/assets/93918596/10fd7eda-fb7f-4f26-bf84-dd9cf5ac1ec3)

2023-08-04 14:24 UTC, ccamel commented on src/scss/main.scss
> +    border-color: #00b6b7 transparent;
Yes. I see. It's fine. Thanks.

2023-08-04 14:25 UTC, ccamel approved these changes
LGTM! :+1:

2023-08-04 16:55 UTC, fredericvilcot requested changes

2023-08-04 16:55 UTC, fredericvilcot commented on src/scss/main.scss
> +}
The `mixin` name suggests a generic behavior that could be used anywhere in any stylesheet.

But, AFAIS, it's coupled to the `--ifm-navbar-item-color` CSS variable.

So, I'll suggest to that the function takes an argument to generify its use.

2023-08-04 16:55 UTC, fredericvilcot commented on src/scss/main.scss
> +      color: inherit !important;
`!important` is the very last solution in case of context failure.

Did you try to bring more context by nesting elements and thus avoid this usage?

2023-08-09 08:38 UTC, lolottetheclash approved these changes
thanks !

2023-08-09 09:17 UTC, ccamel approved these changes

2023-08-09 09:51 UTC, merged