feat(whitepaper): add tutorials && Tech doc cards
okp4/docs pull request #285
Opened 2023-08-03 13:21 UTC by houssemmimoun27

This PR add the Tutorials and Technical documentation cards to the home page.

<details>

<summary> Screenshots </summary>

![Screenshot 2023-08-03 at 14 22 13](https://github.com/okp4/docs/assets/93918596/0d949794-7378-4fed-8969-85974e9f02be)

</details>

2023-08-03 13:41 UTC, MdechampG requested changes
Thanks @houssemmimoun27 
Could you keep the same gap between the 2 rows as here : 

![image](https://github.com/okp4/docs/assets/92780073/afc43ad9-704a-4337-8004-4f27759f1c9f)

2023-08-03 15:43 UTC, ccamel commented on docs/index.mdx
> +          <h2>Technikal Documentation</h2>
```suggestion
          <h2>Technical Documentation</h2>

```

2023-08-03 16:26 UTC, ccamel approved these changes
LGTM

2023-08-04 09:50 UTC, fredericvilcot requested changes

2023-08-04 09:50 UTC, fredericvilcot commented on docs/index.mdx
> +        <p class="card-text">Deep dive into the OKP4 protocol.</p>
To be compliant with content at line 47, I'll recommend to capitalize the `protocol` word:
```suggestion
        <p class="card-text">Deep dive into the OKP4 Protocol.</p>

```

2023-08-04 10:49 UTC, fredericvilcot approved these changes
👍

2023-08-04 11:04 UTC, merged