refactor: customize burger menu on right side
okp4/docs pull request #290
Opened 2023-08-11 11:34 UTC by houssemmimoun27

This PR  update the toggle button for the navbar on mobile to be on the right side of the screen instead of the left side.

<details>

![Screenshot 2023-08-11 at 12 27 43](https://github.com/okp4/docs/assets/93918596/2260999c-1548-4ef7-a803-ba828fb84a37)

<summary> Screenshots </summary>

2023-08-11 11:56 UTC, lolottetheclash reviewed
I have a doubt about the implementation of this ticket.:
the burger menu is now on the right side but does it make sense to leave the appearance and disappearance of the menu on the left side (therefore opposite?). 
Do we have a directive from the product team on this?

2023-08-11 12:23 UTC, houssemmimoun27 commented
> I have a doubt about the implementation of this ticket.: the burger menu is now on the right side but does it make sense to leave the appearance and disappearance of the menu on the left side (therefore opposite?). Do we have a directive from the product team on this?

I have no feedback about the implementation of the sidebar from the product team. In my opinion, to improve the user experience the menu must be on the right side like you said. What do you think ?

2023-08-11 12:47 UTC, lolottetheclash commented
> > I have a doubt about the implementation of this ticket.: the burger menu is now on the right side but does it make sense to leave the appearance and disappearance of the menu on the left side (therefore opposite?). Do we have a directive from the product team on this?
> 
> I have no feedback about the implementation of the sidebar from the product team. IMHO, to improve the user experience the menu must be on the right side like you said.
> 
> @lolottetheclash What do you think ?

@houssemmimoun27 It makes more sense to me yes. Can you make the changes please: burger menu on the right, and menu opening/closing on the right side too. (pay attention to details to change in it like arrows directions ^^)

2023-08-13 20:57 UTC, ccamel requested changes

2023-08-13 20:57 UTC, ccamel commented on src/scss/main.scss
> +  }
Nope. You've tried to *hack* the default styles by hidding so you can override the default styles with yours. But the changes are still visible in the DOM, which is not so great:

<img width="482" alt="image" src="https://github.com/okp4/docs/assets/9574336/11ab0a54-4549-4eb0-9d36-2d7847c39fe6">

But more important (not to say critical), there's an issue with internationalization. While most of the text is internationalized in Docusaurus, your `Back to main menu` content isn't. Docusaurus operates on a specific customization logic. It's crucial to understand it before making modifications to the CSS, as doing so recklessly can degrade functionality and potentially render the project difficult to maintain.

For context, the button you're attempting to customize is defined here:

[MobileSidebar/SecondaryMenu/index.tsx](https://github.com/facebook/docusaurus/blob/a59aead1e2732a6d7ceb83f881c0945abca4d696/packages/docusaurus-theme-classic/src/theme/Navbar/MobileSidebar/SecondaryMenu/index.tsx#L17)

Within this code, there's an implemented translation mechanism.

So, read the following documentation, it will help you understand how to implement this correctly:

https://docusaurus.io/docs/i18n/introduction

2023-08-16 08:54 UTC, lolottetheclash requested changes
almost there!

2023-08-16 08:54 UTC, lolottetheclash commented on i18n/fr/code.json
> +    "description": "The label of the back button to return to main menu, inside the mobile navbar sidebar secondary menu (notably used to display the docs sidebar)"
Even if it's just a description, it feels strange to have an english description in a french file

2023-08-16 09:44 UTC, ccamel requested changes

2023-08-16 09:44 UTC, ccamel commented on src/theme/Navbar/MobileSidebar/SecondaryMenu/index.js
> +import React from 'react'
I don't see the point of re-declaring the component [identical](https://github.com/facebook/docusaurus/blob/a59aead1e2732a6d7ceb83f881c0945abca4d696/packages/docusaurus-theme-classic/src/theme/Navbar/MobileSidebar/SecondaryMenu/index.tsx#L17) here. It should work without it.

2023-08-16 09:48 UTC, ccamel requested changes

2023-08-16 09:48 UTC, ccamel commented on src/theme/Navbar/MobileSidebar/SecondaryMenu/index.js
> +function SecondaryMenuBackButton(props) {
Please choose `TypeScript` consistently over `JS`, given Docusaurus's exemplary `TypeScript` support: https://docusaurus.io/docs/typescript-support.

2023-08-16 12:56 UTC, houssemmimoun27 commented on src/theme/Navbar/MobileSidebar/SecondaryMenu/index.js
> +import React from 'react'
To customize the top back button in Docusaurus, we must swizzle the `SecondaryMenu` component by ejecting a copy of the original component. You can check the documentation here [https://docusaurus.io/docs/swizzling#do-i-need-to-swizzle](https://docusaurus.io/docs/swizzling#do-i-need-to-swizzle)

2023-08-16 14:29 UTC, houssemmimoun27 commented on src/theme/Navbar/MobileSidebar/SecondaryMenu/index.js
> +import React from 'react'
To customize the top back button in Docusaurus, we must swizzle the `SecondaryMenu` component by ejecting a copy of the original component. You can check the documentation here [https://docusaurus.io/docs/swizzling#do-i-need-to-swizzle](https://docusaurus.io/docs/swizzling#do-i-need-to-swizzle)

2023-08-16 14:44 UTC, ccamel commented on src/theme/Navbar/MobileSidebar/SecondaryMenu/index.js
> +import React from 'react'
This is true if you intend to customize the button. But correct me if I'm wrong, but it's not necessary if you simply provide the correct translation. So my recommendation would be to simply remove this component and rely solely on CSS cusomization and translations, which is the [official recommendation](https://docusaurus.io/docs/swizzling#do-i-need-to-swizzle). This should work.

2023-08-16 15:10 UTC, houssemmimoun27 commented on src/theme/Navbar/MobileSidebar/SecondaryMenu/index.js
> +import React from 'react'
So, I see the point now. What you mean that no need to customize the button component just adding the configuration  for translation in `docusaurus.config.js` and then changing the button text content via the translation keys in `i18n` json files.

2023-08-17 08:48 UTC, ccamel approved these changes
LGTM! Thanks.

2023-08-17 08:51 UTC, ccamel commented
@lolottetheclash I will let you do the merge because as soon as it's merged, it's deployed, without any safety net. So we have to be sure that the PR has been well tested before. Thanks :pray:

2023-08-17 08:52 UTC, lolottetheclash commented
> @lolottetheclash I will let you do the merge because as soon as it's merged, it's deployed, without any safety net. So we have to be sure that the PR has been well tested before. Thanks 🙏

Sure, I'm already on it :)

2023-08-17 09:34 UTC, lolottetheclash approved these changes
Works well, thanks !

2023-08-17 09:34 UTC, merged