style: improve style mermaid diagrams light/dark mode
okp4/docs pull request #293
Opened 2023-08-25 13:49 UTC by houssemmimoun27

This PR enhance the syle for `mermaid diagrams` for dark and light mode by rendering the colors defined by `OKP4/UI`.
<details>

![Screenshot 2023-08-25 at 14 14 51](https://github.com/okp4/docs/assets/93918596/447a3856-c622-4b1d-8b4b-3c8fe7c63260)

![Screenshot 2023-08-25 at 14 15 07](https://github.com/okp4/docs/assets/93918596/0b5cca55-be65-4c2e-8447-71995ea7e511)

<summary> Screenshots </summary>

2023-08-30 15:59 UTC, fredericvilcot requested changes

2023-08-30 15:59 UTC, fredericvilcot commented on src/scss/main.scss
> +    stroke: var(--ifm-graph-base-line-color) !important;
@houssemmimoun27 
By doing this, you  say you want to apply to all `svg` paths a color defined by this variable.

But, is this what we want? I'm not sure.

As an example, this line of code has modified the burger menu icon:

Before:
<img width="205" alt="Capture d’écran 2023-08-30 à 17 55 50" src="https://github.com/okp4/docs/assets/47554752/06696223-f684-46ba-810c-2ee24dafbabb">

After:
<img width="205" alt="Capture d’écran 2023-08-30 à 17 56 18" src="https://github.com/okp4/docs/assets/47554752/f980d374-4159-4964-bafc-c87c93d2a763">

Please be careful, and don't forget that the `!important` instruction overrides any style with any context in any stylesheet.

2023-08-30 15:59 UTC, fredericvilcot commented on src/scss/main.scss
> +      stroke: var(--ifm-graph-base-actor-color) !important;
Same here, style from all circles included in the group will be modified

2023-08-30 15:59 UTC, fredericvilcot commented on src/scss/main.scss
> +  }
Same here

2023-08-31 14:53 UTC, ccamel approved these changes
LGTM!

2023-09-01 13:46 UTC, fredericvilcot approved these changes
Looks better, thanks

2023-09-01 14:35 UTC, fredericvilcot commented
@MdechampG 
Is this PR ok for you?

2023-09-04 15:45 UTC, MdechampG requested changes
It is working on the mermaid shown in screenshot but not on the ones in the part Technical documentation/Ontology/Ontology principles. 

![image](https://github.com/okp4/docs/assets/92780073/05bcb742-167f-4855-b6c5-b53d83cf9c4d)

2024-01-07 17:27 UTC, ccamel commented
As a result of #371, the latest updates to the [Mermaid](https://mermaid.js.org/) plugin, along with the newest version v3 of [Docusaurus](https://docusaurus.io/) which is now configured with the [@docusaurus/theme-mermaid](https://docusaurus.io/docs/next/api/themes/@docusaurus/theme-mermaid) theme, have enhanced the compatibility of mermaid diagrams for both dark and light modes. Given this upgrade, which effectively renders this PR redundant, I recommend its closure. Should there be a need for cosmetic modifications, a new ticket can be opened and addressed, keeping in mind these recent updates.

fyi @MdechampG

2024-01-07 17:27 UTC, closed without merging