docs: add dataspace business model
okp4/docs pull request #54
Opened 2022-06-16 11:48 UTC by ljacquin

2022-06-16 12:24 UTC, amimart requested changes
Thanks for contributing! 😉 

I'll have some remarks though, as we seek to do things properly:

I see a `.idea` folder has been committed which, in my opinion, brings nothing to this repository so please remove it. Maybe we could consider adding this folder in the root `.gitignore` if many contributors are editing sources through Jetbrains solutions.

Concerning readability and to help reviewers and potential future history explorers understand the changes you're bringing, I'll appreciate, if you don't mind, a brief explanation on the proposed changes. By the way, I see the branch name and commit message are well formed, but I would change the `docs` prefix by `feat`, as the documentation is the very purpose of this repository.

2022-06-16 12:24 UTC, amimart commented on docs/whitepaper/ds-business-models.md
> +The templates are available here : [https://github.com/okp4/kg-comput/blob/docs/theory/kg_comput_latex/kg-comput.pdf](https://github.com/okp4/kg-comput/blob/docs/theory-fr/kg_comput_latex/kg-comput.p
I have a 404 on this link. Besides, it seems to point to a private repository, which isn't suitable for a public documentation, it also point on a non `main` branch which isn't stable enough.

I highly recommend to not reference resources from others repositories directly, for static content we can directly add them into the repository. When referencing external resources prefer those published by other means than repository's blob (e.g. static website, github pages, github release, etc..).

A last remark concerning this pdf file, I found out it was written in french. Please, give preference to english in every resources you refer to.

2022-06-16 12:54 UTC, ccamel commented on docs/whitepaper/ds-business-models.md
> +The templates are available here : [https://github.com/okp4/kg-comput/blob/docs/theory/kg_comput_latex/kg-comput.pdf](https://github.com/okp4/kg-comput/blob/docs/theory-fr/kg_comput_latex/kg-comput.p
I would add that regarding the PDF document in question, since it is a corporate document, it should be ensured that it respects the publication policy, i.e. uses (as much as possible) the corporate charter, has no personal/individual references, clearly mention the license that applies and has a version tracking.

2022-06-16 12:56 UTC, ccamel commented
Please, if you don't mind, can you put a comment in the PR describing its purpose (even if it's obvious). Many thanks.

2022-06-16 13:43 UTC, ljacquin commented
The purpose of this PR is to add the description of the DS business models proposed by OKP4

2022-06-17 07:40 UTC, ccamel commented
@ljacquin Don't hesitate to ask for help if you feel you need it. 😌

2022-06-22 08:25 UTC, ljacquin reviewed
Seems fine for me

2022-06-22 08:58 UTC, ccamel commented
@ljacquin not quite. 🧐 As far as I see, the folder `.idea` is still committed in the PR (see: [changes](https://github.com/okp4/docs/pull/54/files)), and the first commit comment is still prefixed by `docs:`.

In such situation, I think the best thing would be to merge the two commits into one and amend it (remove all unwanted files) We can help you with the procedure if you want. 😌

2022-06-22 11:22 UTC, MdechampG approved these changes

2022-06-22 13:41 UTC, tpelliet approved these changes
OK for me on this draft. It needs to be more explicit though, especially in the data-based pricing templates.

2022-06-27 07:23 UTC, ccamel approved these changes

2022-06-27 07:25 UTC, amimart approved these changes

2022-06-27 07:32 UTC, ccamel commented
Everything is ok (finally)! Let's merge. Thanks to all. 👍

2022-06-27 07:32 UTC, merged