Ci/lint english
okp4/docs pull request #68
Opened 2022-07-04 17:45 UTC by hleonardtek

Implement an english linter to check the spelling of the whitepaper files.

- Full errors location described in the action logs
- Report sent by mail and/or in the PR

2022-07-04 20:16 UTC, ccamel requested changes

2022-07-05 06:29 UTC, ad2ien requested changes
Nice thanks, maybe let's just fix the version.

2022-07-05 06:29 UTC, ad2ien commented on .github/workflows/spellcheck.yml
> +      - uses: check-spelling/check-spelling@main
Souldn't we settle the version?
```suggestion
      - uses: check-spelling/check-spelling@v0.0.20-alpha5
```

2022-07-05 06:29 UTC, ad2ien commented on .github/workflows/spellcheck.yml
> +          extra_dictionaries:
What happens if we remove these?

2022-07-05 07:11 UTC, hleonardtek commented on .github/workflows/spellcheck.yml
> +          extra_dictionaries:
Effectively we can remove the `experimental_apply_changes_via_bot`.
However, `experimental_path` is used to check only certain files (here the whitepaper folder), and `extra_dictionaries` is used for external dictionaries. If we remove them we will have to build our own dictionary for basic stuff (words such as "http", "https", etc)

2022-07-05 07:27 UTC, hleonardtek commented on .github/workflows/spellcheck.yml
> +      - uses: check-spelling/check-spelling@main
I will put the last one, i.e v0.0.20-alpha7.
Thanks !

2022-07-05 08:04 UTC, ad2ien approved these changes
Ok for me!

2022-07-13 05:53 UTC, ad2ien commented on .github/workflows/spellcheck.yml
> +          experimental_path: docs/whitepaper
@hleonardtek actually Anik should be the one commenting the PR

```suggestion
          GITHUB_TOKEN: ${{ secrets.OKP4_TOKEN }}
```

2022-07-13 07:11 UTC, amimart commented
Regarding the comments it did on this PR, I'm not really convinced this linter will be helpful.. Maybe a cron job opening a new PR with spelling and grammar suggestions would fit much, what do you think ?

2022-07-13 08:21 UTC, ccamel commented
If you don't mind, I put the PR in draft while we agree on the best approach. Thx.

2022-07-13 09:09 UTC, ad2ien commented
> Regarding the comments it did on this PR, I'm not really convinced this linter will be helpful.. Maybe a cron job opening a new PR with spelling and grammar suggestions would fit much, what do you think ?

I though it was nice to have a comment on the PR, it gives people a chance to correct their typos. Maybe with a better template?
Opening a PR without changes? an issue maybe then?

2022-07-20 07:49 UTC, hleonardtek commented
Yes effectively,  like I wrote in the issue, this action doesn't provide relevant information concerning the errors. It only prints the misspelled words in the PR, without the concerned files and precise locations.
However, we could build our own action, or even a CJ as said by @amimart.
In my view, an action is more suitable as it will be triggered on changes only.

What are the advantages of a CronJob compared to an action ?

2024-01-07 17:32 UTC, ccamel commented
@amimart still relevant?

2024-01-07 17:52 UTC, amimart commented
@ccamel Would have been great, but seems difficult to continue so I'm in favour of closing it.

2024-01-07 18:33 UTC, closed without merging