Ci/lighthouse workflow
okp4/docs pull request #79
Opened 2022-07-22 14:48 UTC by nperon

2022-08-05 07:54 UTC, amimart requested changes
A just have a single remark

2022-08-05 07:54 UTC, amimart commented on .github/workflows/lint.yml
> +          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```suggestion
          GITHUB_TOKEN: ${{ secrets.OKP4_TOKEN }}
```

Can we use [bot-anik](https://github.com/bot-anik)'s token instead for commenting the PR ?

2022-08-05 11:45 UTC, nperon commented on .github/workflows/lint.yml
> +          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
Correction for OKP4_TOKEN is now made everywhere.

2022-09-23 20:43 UTC, fredericvilcot commented
@nperon I think we could put this PR as draft as it's not ready to review yet.

2023-05-04 12:35 UTC, ccamel commented
Outdated. The functionality will be reintroduced using the recipe implemented in https://github.com/okp4/dataverse-portal/pull/57.

2023-05-04 12:35 UTC, closed without merging