Feat: sentry node architecture
okp4/docs pull request #88
Opened 2022-08-09 10:06 UTC by ingvaar

Add the **sentry node architecture** section in the `nodes/security` part of the documentation.
It provides a schematic describing the architecture and some precision on how to implement it.
It is lightweight because their is already some documentation on how to deploy a single node.

2022-08-09 14:13 UTC, ccamel reviewed
Please provide the diagram as an [mxfile](https://app.diagrams.net) diagram embedded with the `Drawio` react component. This will make it easier to edit the diagram later by having its source format available.

2022-08-09 14:16 UTC, amimart requested changes
This is an important and complex part, network security shall be our priority, thanks to initiate this.

I think we should go further in the details, maybe even point to other existing documentations, there's already some good literature on this subject.

Regarding the structure, I think we could divide it in multiple sections, it'll bring a more logical path and divide the complexity.

2022-08-09 14:16 UTC, amimart commented on docs/nodes/security.md
> +While deploying a node, the validator should never go down.
As an introduction word, I think we should detail how critical a validator is and the risks it has when exposed, and then propose a solution, not the only solution but the one we recommend. Because the security of the network is a matter of every operator.

2022-08-09 14:16 UTC, amimart commented on docs/nodes/security.md
> +![architecture schematic](/img/content/nodes/sna.png)
Docusaurus support draw.io xml schema, I'd prefer integrate these formats instead.

Regarding the content of this schema, I think it contains too much informations and detailed that doesn't belong to the sentry node architecture, we can simplify it.

2022-08-09 14:16 UTC, amimart commented on docs/nodes/security.md
> +This architecture places the **validator** behind 3 **sentries**.
The sentry node architecture isn't strict on the number of sentries, this ideal is even having it scalable through dynamic provisioning. However, I think we can recommend a minimum of 3 nodes as it is a standard recommendation regarding resiliency.

2022-08-09 14:16 UTC, amimart commented on docs/nodes/security.md
> +The validator must have a persistent storage, it will hold the blockchain.
All the nodes shall have persistent storage 😉

2022-08-09 14:16 UTC, amimart commented on docs/nodes/security.md
> +The API will be load balanced via the sentries and each of them will expose a peer-to-peer port.
Exposing APIs through the sentry isn't mandatory, the very purpose of the sentry node architecture is just to isolate the validator node from outside while being part of the P2P protocol.

2022-08-09 14:16 UTC, amimart commented on docs/nodes/security.md
> +- Each sentry and the validator must have their persistent peers set to each other's
About the configuration of the different nodes, maybe we can directly give the config parameters to set, it could be practical to have concrete example.

2022-08-09 14:24 UTC, ccamel commented on docs/nodes/security.md
> +While deploying a node, the validator should never go down.
Not specific enough. Describe the risk and mitigation measures: prevent network attacks (DDoS, brute force..) from being launched directly against a validator network

2022-08-09 14:24 UTC, ccamel commented on docs/nodes/security.md
> +This architecture places the **validator** behind 3 **sentries**.
I'd like to have a section for a sentry. And describe that a sentry node is simply a full node, accessible over the public internet, that connects to the blockchain and relays the chain to the validator.  Mention also that this ensures the validator network information remains hidden and will never be accessible over the public internet. Insist on security (why, how), including isolation of public/private networks, etc...

2024-01-07 17:31 UTC, ccamel commented
@amimart @MdechampG still relevant?

2024-01-07 17:50 UTC, amimart commented
@ccamel Not really, I think we can close this one.

2024-01-07 18:33 UTC, closed without merging