Feat: join testnet
okp4/docs pull request #89
Opened 2022-08-09 10:07 UTC by ingvaar

Add the `nodes/join-testnet` part of the documentation.

2022-08-09 13:30 UTC, amimart requested changes
Thanks for initiating this documentation!

This is difficult to document this part as there is no testnet available yet, I made some remarks to correct some informations and denote some that doesn't belong in this section, in my opinion.

@ccamel The testnet being currently on the road, I propose to keep this PR in draft, and keep it up to date with every new informations concerning it, to finally merge it as soon as it is alive!

2022-08-09 13:30 UTC, amimart commented on docs/nodes/join-testnet.md
> +It will allow the node to process requests made on the blockchain.
Regarding the deployment of a validator node, we do not recommend to expose any API.

2022-09-27 05:29 UTC, bdeneux requested changes
Just a small spelling mistake 😊.

2022-09-27 05:29 UTC, bdeneux commented on docs/nodes/join-testnet.md
> +Please fin below the minimum recommended hardware configuration for running a testnet `okp4d` node:
```suggestion
Please find below the minimum recommended hardware configuration for running a testnet `okp4d` node:
```

2022-09-27 13:27 UTC, bdeneux approved these changes

2022-09-27 14:28 UTC, ccamel approved these changes
👍

2022-09-27 17:00 UTC, amimart requested changes

2022-09-27 17:00 UTC, amimart commented on docs/nodes/join-testnet.mdx
> +      <td align="center">{data.okp4dVersion}</td>
It may be better to statically write it there, as all networks are not likely to share the same version of `okp4d`.

2022-09-27 20:12 UTC, amimart approved these changes

2022-09-27 20:12 UTC, merged